name: build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get History
        id: get_history
        run: |
          chmod +x history.sh
          output=$(./history.sh)
          echo "$output" > history.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body_path: history.md

      - name: Gitee Create Release
        run: |
          latest_commit=$(git rev-parse HEAD)
          history=$(cat history.md)
          curl -v POST https://gitee.com/api/v5/repos/${{ github.repository }}/releases \
          -H "Content-Type: application/json" \
          -d '{
            "access_token": "${{ secrets.GITEE_ACCESS_TOKEN}}",
            "tag_name": "${{ github.ref_name }}",
            "name": "Release ${{ github.ref_name }}",
            "body": "'"$history"'",
            "prerelease": false,
            "target_commitish": "'"$latest_commit"'"
          }'